name: Clinic Web Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./ProfiraClinicWeb/ProfiraClinicWeb/ProfiraClinicWeb.csproj

      - name: Build
        run: dotnet build ./ProfiraClinicWeb/ProfiraClinicWeb/ProfiraClinicWeb.csproj --configuration Debug --no-restore
